[package]
name = "md-crdt-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
bincode = "1.3.3"
crc32fast = "1.5.0"

[dev-dependencies]
tempfile = "3.24.0"
