name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Install just
      run: cargo install just

    - name: Check formatting
      run: just fmt

    - name: Lint code
      run: just lint

    - name: Run tests
      env:
        PROPTEST_CASES: 100000
      run: just test

    - name: Differential tests
      run: just differential-test

  nightly-differential-test:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Install just
      run: cargo install just

    - name: Differential tests (nightly)
      env:
        PROPTEST_CASES: 1000000
      run: just differential-test

    - name: Run tests (nightly)
      env:
        PROPTEST_CASES: 1000000
      run: just test
